export const UPDATE_EDITOR_STATE="UPDATE_EDITOR_STATE";
export const TOOGLE_BLOCK_TYPE="TOOGLE_BLOCK_TYPE";
export const TOOGLE_INLINE_STYLE="TOOGLE_INLINE_STYLE";
export const INSERT_IMAGE="INSERT_IMAGE";
export const ALINGMENT_IMAGE="ALINGMENT_IMAGE";